### ISSUE TITLE
Issue:    float() argument must be a string or a number, not 'Timestamp'

### ISSUE THREAD

**Issue by shaoy06** [happydasch/btplotting#18]
Hi happydasch,
When I plot, I always have following issue:
![image](https://user-images.githubusercontent.com/87840832/131769314-97bd1d3d-44af-434b-a505-95ac1bc8c872.png)

Could you please help? Many thanks! 

`        data = store.getdata(
            dataname='%s/%s' % (COIN_TARGET, COIN_REFER),
            name='%s%s' % (COIN_TARGET, COIN_REFER),
            timeframe=bt.TimeFrame.Minutes,
            fromdate=hist_start_date,
            compression=1,
            ohlcv_limit=99999,
            drop_newest = True,
            nullvalue=0.0
        )

        cerebro.adddata(data)
        cerebro.replaydata(data,timeframe=bt.TimeFrame.Minutes,compression=30,name='30_min')`

**Comment by happydasch** [comment]
already fixed in latest code

**Comment by shaoy06** [comment]
> already fixed in latest code

Actually I am using the version 0.1.1. Not sure this version is the latest code. 
However, the issue still exists. 
Thanks.
